language: node_js
before_script:
  - npm install -g gatsby
cache:
  directories:
    - node_modules
node_js:
  - "10"
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: production
